# FinerPlan Web Server (uWSGI + NGINX)
# References:
# - https://pythonise.com/series/learning-flask/building-a-flask-app-with-docker-compose
# - https://vsupalov.com/docker-env-vars/
version: '3'

services:
  finerplan:
    image: finerplan:0.3.3
    build: .
    env_file:
      - .env
    environment:
      - APP_FOLDER=$APP_FOLDER
      - UWSGI_PORT=$UWSGI_PORT
      - UWSGI_USER=$UWSGI_USER
      - FINERPLAN_SECRET_KEY=$FINERPLAN_SECRET_KEY
    volumes:
      - ./uwsgi.ini:${APP_FOLDER}/uwsgi.ini:ro
      - ./finerplan:${APP_FOLDER}/finerplan:ro
      - ./dev.finerplan.db:${APP_FOLDER}/finerplan.db:rw
    expose:
      - ${UWSGI_PORT}

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./finerplan:/usr/share/nginx/html:ro
    depends_on:
      - finerplan
    ports:
      - 80:80