"""creates installment table

Revision ID: 087878d2621d
Revises: 8ed2729f60b4
Create Date: 2019-08-06 22:53:22.782119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087878d2621d'
down_revision = '8ed2729f60b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('cash_date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('installments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installments', sa.INTEGER(), nullable=True))

    op.drop_table('installment')
    # ### end Alembic commands ###
