"""table transaction

Revision ID: 1feecc8e0bfc
Revises: 279dbcfc74ff
Create Date: 2019-08-08 20:56:23.734610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1feecc8e0bfc'
down_revision = '279dbcfc74ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('accrual_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('cash_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installment')
    op.drop_table('transaction')
    # ### end Alembic commands ###
