"""Card_Reports becomes association table

Revision ID: 21170ffb94a8
Revises: de1f076aeea7
Create Date: 2019-08-08 09:44:26.159205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21170ffb94a8'
down_revision = 'de1f076aeea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_report',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'report_id')
    )
    op.drop_table('card_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=True),
    sa.Column('kind', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_report')
    op.drop_table('report')
    # ### end Alembic commands ###
