"""table account

Revision ID: 279dbcfc74ff
Revises: 1dd806073343
Create Date: 2019-08-08 20:55:40.576254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279dbcfc74ff'
down_revision = '1dd806073343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['accounting_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closing', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card')
    op.drop_table('account')
    # ### end Alembic commands ###
