"""creates account groups table

Revision ID: 362c7b1c7897
Revises: e5ece119a8d9
Create Date: 2019-08-05 13:21:49.237759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362c7b1c7897'
down_revision = 'e5ece119a8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_account_groups_group_id', 'account_groups', ['group_id'], ['id'])
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('fk_account_groups_group_id', type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('account_groups')
    # ### end Alembic commands ###
