"""empty message

Revision ID: 7a9ba651ab5b
Revises: 
Create Date: 2019-06-24 01:35:31.581709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9ba651ab5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('asset_class', sa.String(length=128), nullable=True),
    sa.Column('subclass', sa.String(length=128), nullable=True),
    sa.Column('asset', sa.String(length=128), nullable=True),
    sa.Column('maturity', sa.String(length=128), nullable=True),
    sa.Column('aim_bool', sa.Integer(), nullable=True),
    sa.Column('aim', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brokerage_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accrual_date', sa.DateTime(), nullable=True),
    sa.Column('cash_date', sa.DateTime(), nullable=True),
    sa.Column('custodian', sa.String(length=128), nullable=True),
    sa.Column('origin', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accrual_date', sa.DateTime(), nullable=True),
    sa.Column('cash_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_method', sa.String(length=128), nullable=True),
    sa.Column('accrual_date', sa.DateTime(), nullable=True),
    sa.Column('cash_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('category_1', sa.String(length=128), nullable=True),
    sa.Column('category_2', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('custodian', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('asset', sa.String(length=128), nullable=True),
    sa.Column('carteira', sa.Float(), nullable=True),
    sa.Column('aporte', sa.Float(), nullable=True),
    sa.Column('cotas', sa.Float(), nullable=True),
    sa.Column('valor_cotas', sa.Float(), nullable=True),
    sa.Column('medium_annual_price', sa.Float(), nullable=True),
    sa.Column('medium_historical_price', sa.Float(), nullable=True),
    sa.Column('month_earning', sa.Float(), nullable=True),
    sa.Column('year_earning', sa.Float(), nullable=True),
    sa.Column('total_earning', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('date', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('gross_value', sa.Float(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('value_history')
    op.drop_table('rendimentos')
    op.drop_table('investments')
    op.drop_table('expenses')
    op.drop_table('earnings')
    op.drop_table('brokerage_transfers')
    op.drop_table('assets')
    # ### end Alembic commands ###
