"""renames Card columns

Revision ID: b6f82d089ba7
Revises: 2719f4cec29d
Create Date: 2019-08-07 18:18:15.068501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f82d089ba7'
down_revision = '2719f4cec29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
