"""datetime to date columns

Revision ID: bb91fd27d6b3
Revises: 087878d2621d
Create Date: 2019-08-06 23:46:31.408134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb91fd27d6b3'
down_revision = '087878d2621d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
