"""includes Account.group column

Revision ID: e5ece119a8d9
Revises: b2af183fc727
Create Date: 2019-07-25 15:44:36.623223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ece119a8d9'
down_revision = 'b2af183fc727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('group', sa.String(length=64), nullable=True))
    op.add_column('transaction', sa.Column('installments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'installments')
    op.drop_column('account', 'group')
    # ### end Alembic commands ###
