#!/bin/bash
# Start FinerPlan

set -o errexit

readonly SCRIPT_NAME=$(basename $0)

trap "die 'Cancelled by the user.'" INT
trap "die 'Something went wrong.'" ERR

die(){
  local message=$1
  echo "ERROR: $message" >&2
  exit 1
}

start_dev(){
  # Reduce risk of a misconfigured flask server use other databases
  export FINERPLAN_DATABASE=''
  
  [ -f ".flaskenv" ] && [ -f "wsgi.py" ] && [ -d "finerplan" ] || die "Are you sure '$PWD' is the project folder?"
  nohup flask run > ./finerplan.log 2>&1 &
}

start_prd(){
  check_environment
  uwsgi /etc/uwsgi/apps-enabled/finerplan.ini
}

check_environment(){
  [ ! -z "$FINERPLAN_DATABASE" ] || die "FINERPLAN_DATABASE is null or unset."
  [ -w "$FINERPLAN_DATABASE" ] || die "FINERPLAN_DATABASE is not writable."
  [ ! -z "$FINERPLAN_SECRET_KEY" ] || die "FINERPLAN_SECRET_KEY is null or unset."
}

usage(){
  cat <<EOF
  Start FinerPlan.

usage: $SCRIPT_NAME {development|production}

development       Start FinerPlan using flask server.
production        Start FinerPlan using uWSGI.

EOF
}

main(){
  if [ $# -gt 0 ]; then
    case "$1" in
      development)    start_dev ;;
      production)     start_prd ;;
      *)              usage ;;
    esac
  else
    usage
  fi
}

main "$@"

